### PR TITLE
Don't scroll sub-trace details panel

### PR DESCRIPTION
**Pull request by franzliedke**
On long traces, it was very tricky to investigate subtraces' details. Until now. :)

### CODE REVIEW

**Comment by jgraichen** [comment]
Will it still work when the details include more content than one viewport height?

**Comment by franzliedke** [comment]
Not sure. I couldn't construct such a case. Lemme check.

**Comment by franzliedke** [comment]
Fixed by setting a maximum height and `overflow: auto`.

Also improved the backwards compatibility for browsers that don't know how to deal with `position: sticky`.

**Comment by jgraichen** [comment]
Thanks!

**Pull request merged**
